// <auto-generated />
namespace _19DTHC2_BigSchool_HaiDang_1911065192.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class InnitDb : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(InnitDb));
        
        string IMigrationMetadata.Id
        {
            get { return "202203280428222_Innit Db"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
